Vagrant.configure("2") do |config|

  config.vm.box = "creativeux/centos7-64-docker"

  # Forward the local ports to the webapp and livereload ports.
  config.vm.network :forwarded_port, host: 9000, guest: 9000
  config.vm.network :forwarded_port, host: 35729, guest: 35729

  # Forward the local port to the API.
  config.vm.network :forwarded_port, host: 8080, guest: 8080

  # Pass the web project folder into the VM
  config.vm.synced_folder "./webapp-test", "/webapp"

  # Pass the source folder and local Maven repo into the VM.
  config.vm.synced_folder "./api-test", "/data/src"
  config.vm.synced_folder "~/.m2", "/home/vagrant/.m2"


  # Hack? '--privileged=true' is the only way I was able to get the volumes to map with permissions to run npm installs.
  config.vm.provision "docker" do |d|

      # Pull down and run the Grunt image.  Map it to our host machine for livereload.
      d.pull_images "creativeux/centos-grunt:latest"
      d.run "creativeux/centos-grunt",
        args: "--privileged=true -it -p 9000:9000 -p 35729:35729 -v /webapp:/var/www",
        daemonize: true


      # Pull the Jersey image and run it passing the src dor and local Maven repo through to save time on builds.
      d.pull_images "creativeux/centos-jersey:latest"
      d.run "creativeux/centos-jersey",
              args: "--privileged=true -it -p 8080:8080 -v /data/src:/data -v /home/vagrant/.m2:/root/.m2 creativeux/centos-jersey",
              daemonize: true
    end
end
