Vagrant.configure("2") do |config|

  config.vm.box = "creativeux/centos7-64-docker"

  # Forward the local port to the API.
  config.vm.network :forwarded_port, host: 8080, guest: 8080

  # Pass the source folder and local Maven repo into the VM.
  config.vm.synced_folder "./api-test", "/data/src"
  config.vm.synced_folder "~/.m2", "/home/vagrant/.m2"


  # Hack? '--privileged=true' is the only way I was able to get the volumes to map with permissions to run npm installs.
  config.vm.provision "docker" do |d|

      # Pull the Jersey image and run it passing the src dor and local Maven repo through to save time on builds.
      d.pull_images "creativeux/centos-jersey:latest"
      d.run "creativeux/centos-jersey",
              args: "--privileged=true -it -p 8080:8080 -v /data/src:/data -v /home/vagrant/.m2:/root/.m2 creativeux/centos-jersey",
              daemonize: true
    end
end
