Vagrant.configure("2") do |config|

  config.vm.box = "creativeux/centos7-64-docker"

  # Forward the local ports to the webapp and livereload ports.
  config.vm.network :forwarded_port, host: 9000, guest: 9000
  config.vm.network :forwarded_port, host: 35729, guest: 35729

  # Forward the local port to the API.
  config.vm.network :forwarded_port, host: 8080, guest: 8080

  # Pass the web project folder into the VM
  config.vm.synced_folder "./webapp-test", "/webapp"

  # Hack? '--privileged=true' is the only way I was able to get the volumes to map with permissions to run npm installs.
  config.vm.provision "docker" do |d|

      # Pull down and run the Grunt image.  Map it to our host machine for livereload.
      d.pull_images "creativeux/centos-grunt:latest"
      d.run "creativeux/centos-grunt",
        args: "--privileged=true -it -p 9000:9000 -p 35729:35729 -v /webapp:/var/www",
        daemonize: true


      # Pull the Tomcat image and run it.  The WAR should be built into the image.
      d.pull_images "creativeux/centos-tomcat:latest"
      d.run "creativeux/centos-tomcat",
              args: "-it -p 8080:8080",
              daemonize: true
    end
end
